// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjettlmdcrszrlkcdpuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZXR0bG1kY3JzenJsa2NkcHV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTA4OTgsImV4cCI6MjA2MzA2Njg5OH0.wrZywRK-1LXEb6ivaXVM8u-qt6LI5QTGK9yrDCrnMyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);